### PR TITLE
Create Cozy-Map

### PR DESCRIPTION
**Pull request by jojorb**
Hello here is my cozy app "cozy-map",
i don't know if you want to use the svg icon available on my repo [here](https://github.com/RobyRemzy/cozy-map/blob/master/main_icon.svg) but feel free to change it if you need to.

### CODE REVIEW

**Comment by jojorb** [comment]
Oh i'm also waiting the PR [#259](https://github.com/cozy/cozy-proxy/pull/259) to be able to use Font Awesome above 4.4, thanks

**Comment by frankrousseau** [comment]
Hello Remi. The icon looks fine. But we need to do some functional tests before. We'll check that and come back to you very soon.

**Comment by frankrousseau** [comment]
About the icon it's a little bit too wide. Can you reduce its size by adding blank space around it? If not we'll ask to @kelukelu. 

There is something wrong in your app. It asks for permissions that doesn't relate to anything in Cozy. You should mention here the list of document types accessed by your application. 

Another point, is that with the current version of Cozy Map, I can't store any position. Is that normal?

**Comment by jojorb** [comment]
i had some difficulties to re-master the icon, yes indeed it's a bit wide, it will probably be better if someone can do it clean.

Well yes it's normal for now.
Before to be able to save some POI i want to make sure that the app is ok and basic.
The POI will be saved with Cozysdk as new contact or inside Files later on.

**Comment by jojorb** [comment]
So i should remove the permissions and the version things, right? it's useless if it's not related to Cozy?

**Comment by jojorb** [comment]
@frankrousseau i updated the package.json to fit Cozy permissions. 
I try to update the main_icon please check.

**Comment by jojorb** [comment]
Hello @frankrousseau , i just updated the icon! no glitchy anymore.

**Comment by clochix** [comment]
Ping @frankrousseau, it would be nice to have a quicker review process than some well known proprietary store ;-)

**Comment by frankrousseau** [comment]
Yep, Clochix but I'm still human and I don't want to rush on this one. What you can do with the app is not obvious. So, I still have to think before including it.

**Comment by jojorb** [comment]
let think together!

**Comment by frankrousseau** [comment]
Ok @RobyRemzy here are the new requirements we set:
- Each button that doesn't lead to a working action must be removed.
- An explanation about what does Cozy Map when the app is launched is required.

When I tried the app, I was too much confused by the fact it only allows me to browse a map without setting my own locations.  An explanation at the beginning would have helped.

**Comment by kosssi** [comment]
cozy-map sound like google maps ... but this application is more a map-creator?

**Comment by frankrousseau** [comment]
@kosssi No it's like Google Maps. But I thought it was a point of interest management app.

**Comment by jojorb** [comment]
Thanks for your feedback guys,
@frankrousseau sorry for the confusion, the project attempt to stand on 3 components,
and i'm very early into the project, like into step 1, and need feedbacks or helps.

1- search and render data first! (if you can't search, it make it harder to find it!)
2- ease the contribution to open sourced projects, (create/update what you found)
3- save data. (keep it in your database if you need/want to, with a knowledge of the data)

For me, contributing to osm is very important as well as other side project of the same kind.
it's like enjoy to share/manage with the Cozy techno, and follow the path of Open Source.

So to entertain a little bit the community and gathering some help with a reachable app; 
i thought to push the app into the store, as an early stage, would be good, like an early kind of stable deliver.

NB: Leaflet gonna be in V1.0 in a few weeks so i wish to keep the project very simple (under control) to avoid any wrong path.

**Comment by frankrousseau** [comment]
Yep, thank you @RobyRemzy for the additional information. It makes things clearer. 
Additionnaly, can you remove unactive buttons from the app and add this explanation somewhere in the app?

**Comment by jojorb** [comment]
yes totally make sense i will do that asap, so a modal on startup right? or an icon with a help thing with links to user guide.

**Comment by frankrousseau** [comment]
Yep, a modal  or a help icon will do the job.

**Comment by jojorb** [comment]
hi, ok i done it with some help icons. You can check it with the v0.1.21 right now.
thanks!

**Comment by frankrousseau** [comment]
Thank you @RobyRemzy

**Pull request merged**
