### PR TITLE
Frost

### PR DESCRIPTION
**Pull request by y-lohse**
Hi,
Frost is now stable enough to be published IMO :-)

I'd like to keep using the existing icon if possible, [here it is in svg format](https://github.com/cozy/cozy-registry/files/170398/frosticon.zip). However I did not create it myself, I got it [from here](https://thenounproject.com/search/?q=freeze&i=214113). I've added the credits, but Im unsure how it affects Cozy as a hoster.

### CODE REVIEW

**Comment by frankrousseau** [comment]
Hi @y-lohse,

Thank you for this awesome contribution. Can you put the icon at the SVG format?

**Comment by frankrousseau** [comment]
Oups, sorry I didn't read your message.

**Comment by frankrousseau** [comment]
Thank you @y-lohse for this new app!

**Comment by y-lohse** [comment]
My pleasure! :)

**Pull request merged**
